// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiQa81I0RgWSOAYu6WeYQUGSW8aP6HNE0',
    appId: '1:292886221868:web:cc9216b17d545df2d92d89',
    messagingSenderId: '292886221868',
    projectId: 'project-pilates-53521',
    authDomain: 'project-pilates-53521.firebaseapp.com',
    storageBucket: 'project-pilates-53521.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEkfgO6fycSNvXm2-SZ8Vo_A1W4J4OCyE',
    appId: '1:292886221868:android:c8181a4b95014520d92d89',
    messagingSenderId: '292886221868',
    projectId: 'project-pilates-53521',
    storageBucket: 'project-pilates-53521.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd7EGt1Tge3qoOclBpc7CLSfALMv1T5Xg',
    appId: '1:292886221868:ios:9cb24207af98a864d92d89',
    messagingSenderId: '292886221868',
    projectId: 'project-pilates-53521',
    storageBucket: 'project-pilates-53521.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd7EGt1Tge3qoOclBpc7CLSfALMv1T5Xg',
    appId: '1:292886221868:ios:9cb24207af98a864d92d89',
    messagingSenderId: '292886221868',
    projectId: 'project-pilates-53521',
    storageBucket: 'project-pilates-53521.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiQa81I0RgWSOAYu6WeYQUGSW8aP6HNE0',
    appId: '1:292886221868:web:50bf7acff5c04d7ed92d89',
    messagingSenderId: '292886221868',
    projectId: 'project-pilates-53521',
    authDomain: 'project-pilates-53521.firebaseapp.com',
    storageBucket: 'project-pilates-53521.firebasestorage.app',
  );
}
